package net.sourceforge.squirrel_sql.plugins.i18n;

import net.sourceforge.squirrel_sql.client.IApplication;
import net.sourceforge.squirrel_sql.fw.util.StringManager;
import net.sourceforge.squirrel_sql.fw.util.StringManagerFactory;

import javax.swing.*;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.util.prefs.Preferences;
import java.util.ArrayList;
import java.util.Properties;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.PrintWriter;

public class DevelopersController
{
	private static final StringManager s_stringMgr =
		StringManagerFactory.getStringManager(DevelopersController.class);


	private DevelopersPanel _panel;
	private IApplication _app;
	private static final String PREF_KEY_SOURCE_DIR = "SquirrelSQL.i18n.sourceDir";


	public DevelopersController(DevelopersPanel pnlDevelopers)
	{
		_panel = pnlDevelopers;

		_panel.btnChooseSourceDir.addActionListener(new ActionListener()
		{
			public void actionPerformed(ActionEvent e)
			{
				onChooseSourceDir();
			}

		});

		_panel.btnAppendI18nInCode.addActionListener(new ActionListener()
		{
			public void actionPerformed(ActionEvent e)
			{
				onAppendI18nInCode();
			}
		});


		String sourceDir = Preferences.userRoot().get(PREF_KEY_SOURCE_DIR, null);
		_panel.txtSourceDir.setText(sourceDir);
	}


	private void onChooseSourceDir()
	{
		JFileChooser chooser = new JFileChooser(System.getProperties().getProperty("user.home"));
		chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
		chooser.showOpenDialog(_app.getMainFrame());

		if(null != chooser.getSelectedFile())
		{
			_panel.txtSourceDir.setText(chooser.getSelectedFile().getPath());
		}
	}

	private void onAppendI18nInCode()
	{
		File sourceDir = getSourceDir();

		if(null == sourceDir)
		{
			return;
		}

		appendProps(sourceDir);
	}

	private void appendProps(File sourceDir)
	{
		try
		{
			File[] files = sourceDir.listFiles();

			ArrayList newProps = new ArrayList();
			ArrayList replaceProps = new ArrayList();


			File i18nStringFile = new File(sourceDir, "I18NStrings.properties");
			Properties curProps = new Properties();
			FileInputStream fis;

			if(i18nStringFile.exists())
			{
				fis = new FileInputStream(i18nStringFile);
				curProps.load(fis);
				fis.close();
			}

			for (int i = 0; i < files.length; i++)
			{
				if(files[i].isDirectory())
				{
					appendProps(files[i]);
				}
				else if(files[i].getName().endsWith(".java"))
				{
					StringBuffer code = new StringBuffer();
					fis = new FileInputStream(files[i]);

					int buf = fis.read();
					while(-1 != buf)
					{
						code.append((char)buf);
						buf = fis.read();
					}

					fis.close();


					try
					{
						parseProps(code.toString(),curProps, newProps, replaceProps);
					}
					catch (I18nParseException e)
					{
						Object[] params = new Object[]{files[i].getPath(), e.getMessage()};
						_app.getMessageHandler().showErrorMessage(s_stringMgr.getString("i18n.failedToParse", params));
						// i18n[i18n.failedToParse=Failed to parse {0}\n{1}]
						continue;
					}

					if(0 < newProps.size() || 0 <replaceProps.size())
					{
						FileOutputStream fos = new FileOutputStream(i18nStringFile, true);
						PrintWriter ps = new PrintWriter(fos);

						// No i18n, developers should write English props.
						ps.println("\n#\n#Missing properties generated by I18n Plugin on " + new java.util.Date() + "\n#");

						for (int j = 0; j < newProps.size(); j++)
						{
							ps.println(newProps.get(j));
						}

						for (int j = 0; j < replaceProps.size(); j++)
						{
							// No i18n, developers should write English props.
							ps.println("# A T T E N T I O N: REPLACES SAME KEY ABOVE");
							ps.println(replaceProps.get(j));
						}

						ps.flush();
						fos.flush();
						ps.close();
						fos.close();

						Object[] params = new Object[]{new Integer(newProps.size()), new Integer(replaceProps.size()), files[i].getPath()};

						_app.getMessageHandler().showMessage(s_stringMgr.getString("i18n.parseSuccess", params));
						// i18n[i18n.parseSuccess=Parsed {0} new and {1} replaced properties from {2}]


					}

				}
			}
		}
		catch (Exception e)
		{
			throw new RuntimeException(e);
		}

	}

	private void parseProps(String code, Properties curProps, ArrayList newProps, ArrayList replaceProps) throws I18nParseException
	{
		code = code.replace('\r', ' ');

		Pattern pat = Pattern.compile("//\\x20*i18n\\[(.*)");
		Matcher m = pat.matcher(code);

		int[] propBounds = new int[]{0,0};

		while(m.find(propBounds[1]))
		{
			propBounds[0] = m.start(m.groupCount());
			String prop = getProp(code, propBounds);

			int equalsPos = prop.indexOf('=');
			if(0 > equalsPos)
			{
				throw new I18nParseException("Property " + prop + " has no key.");
			}
			String key = prop.substring(0, equalsPos);
			String val = prop.substring(equalsPos + 1);

			if(curProps.containsKey(key) && false == val.equals(I18nUtils.normalizePropVal((String) curProps.get(key))))
			{
				replaceProps.add(prop);
			}
			else if(false == curProps.containsKey(key))
			{
				boolean found = false;
				for (int i = 0; i < newProps.size(); i++)
				{
					if(((String)newProps.get(i)).startsWith(key))
					{
						found = true;
						replaceProps.add(prop);
						break;
					}

				}

				if(false == found)
				{
					newProps.add(prop);
				}

			}
		}

	}

	private String getProp(String code, int[] propBounds) throws I18nParseException
	{
		boolean isInComment = true;
		boolean isABracket = false;
		boolean isASlash = false;

		StringBuffer ret = new StringBuffer();


		for(int i=propBounds[0]; i < code.length(); ++i)
		{
			if(isInComment && isABracket && ']' != code.charAt(i))
			{
				if(isABracket)
				{
					propBounds[1] = i;
					return I18nUtils.normalizePropVal(ret.toString());
				}
			}
			else if(isInComment && ']' == code.charAt(i))
			{
				if(isABracket)
				{
					ret.append(']');
				}
				isABracket = !isABracket;
				isASlash = false;
			}
			else if(isInComment && '\n' == code.charAt(i))
			{
				isInComment = false;
				isABracket = false;
				isASlash = false;
			}
			else if(false == isInComment && false == isASlash && '/' == code.charAt(i))
			{
				isASlash = true;
				isABracket = false;
			}
			else if(false == isInComment && isASlash && '/' == code.charAt(i))
			{
				isInComment = true;
				isABracket = false;
				isASlash = false;
			}

			if(isInComment && false == isABracket)
			{
				ret.append(code.charAt(i));
			}
		}

		if(ret.toString().length() > 50)
		{
			ret.setLength(50);
		}


		throw new I18nParseException("Property " + ret.toString() + " does not end with ]");
	}


	private File getSourceDir()
	{
		String buf = _panel.txtSourceDir.getText();
		if(null == buf || 0 == buf.trim().length())
		{
				String msg = s_stringMgr.getString("I18n.NoSourceDir");
				// i18n[I18n.NoSourceDir=Please choose a source directory.]
				JOptionPane.showMessageDialog(_app.getMainFrame(), msg);
			return null;

		}


		File sourceDir = new File(buf);
		if(false == sourceDir.isDirectory())
		{
				String msg = s_stringMgr.getString("I18n.SourceDirIsNotADirectory", sourceDir.getPath());
				// i18n[I18n.SourceDirIsNotADirectory=Source directory {0} is not a directory.]
				JOptionPane.showMessageDialog(_app.getMainFrame(), msg);
		}

		if(false == sourceDir.exists())
		{
			String msg = s_stringMgr.getString("I18n.SourceDirDoesNotExist", sourceDir.getPath());
			// i18n[I18n.SourceDirDoesNotExist=Source directory {0} does not exist.]
			return null;
		}

		return sourceDir;
	}


	public void initialize(IApplication app)
	{
		_app = app;
	}

	public void uninitialize()
	{
		Preferences.userRoot().put(PREF_KEY_SOURCE_DIR, _panel.txtSourceDir.getText());
	}



}
