DROP TABLE BIGINT_TYPE_TABLE;
DROP TABLE BINARY_TYPE_TABLE;
DROP TABLE BIT_TYPE_TABLE;
DROP TABLE BLOB_TYPE_TABLE;
DROP TABLE BOOLEAN_TYPE_TABLE;
DROP TABLE CHAR_TYPE_TABLE;
DROP TABLE CLOB_TYPE_TABLE;
DROP TABLE DATE_TYPE_TABLE;
DROP TABLE DECIMAL_TYPE_TABLE;
DROP TABLE DOUBLE_TYPE_TABLE;
DROP TABLE FLOAT_TYPE_TABLE;
DROP TABLE INTEGER_TYPE_TABLE;
DROP TABLE LONGVARBINARY_TYPE_TABLE;
DROP TABLE LONGVARCHAR_TYPE_TABLE;
DROP TABLE NUMERIC_TYPE_TABLE;
DROP TABLE REAL_TYPE_TABLE;
DROP TABLE SMALLINT_TYPE_TABLE;
DROP TABLE TIME_TYPE_TABLE;
DROP TABLE TIMESTAMP_TYPE_TABLE;
DROP TABLE TINYINT_TYPE_TABLE;
DROP TABLE VARBINARY_TYPE_TABLE;
DROP TABLE VARCHAR_TYPE_TABLE;


CREATE TABLE BIGINT_TYPE_TABLE
(
   BIGINT_COLUMN bigint
);
CREATE TABLE BINARY_TYPE_TABLE
(
   BINARY_COLUMN binary(8300)
);
CREATE TABLE BIT_TYPE_TABLE
(
   BIT_COLUMN tinyint
);
CREATE TABLE BLOB_TYPE_TABLE
(
   BLOB_COLUMN varbinary(4194304)
);
CREATE TABLE BOOLEAN_TYPE_TABLE
(
   BOOLEAN_COLUMN tinyint
);
CREATE TABLE CHAR_TYPE_TABLE
(
   CHAR_COLUMN char(8300)
);
CREATE TABLE CLOB_TYPE_TABLE
(
   CLOB_COLUMN varchar(4194304)
);
CREATE TABLE DATE_TYPE_TABLE
(
   DATE_COLUMN DATE
);
CREATE TABLE DECIMAL_TYPE_TABLE
(
   DECIMAL_COLUMN decimal(40,20)
);
CREATE TABLE DOUBLE_TYPE_TABLE
(
   DOUBLE_COLUMN double
);
CREATE TABLE FLOAT_TYPE_TABLE
(
   FLOAT_COLUMN float
);
CREATE TABLE INTEGER_TYPE_TABLE
(
   INTEGER_COLUMN integer
);
CREATE TABLE LONGVARBINARY_TYPE_TABLE
(
   LONGVARBINARY_COLUMN varbinary(4194304)
);
CREATE TABLE LONGVARCHAR_TYPE_TABLE
(
   LONGVARCHAR_COLUMN varchar(4194304)
);
CREATE TABLE NUMERIC_TYPE_TABLE
(
   NUMERIC_COLUMN numeric(40,20)
);
CREATE TABLE REAL_TYPE_TABLE
(
   REAL_COLUMN float
);
CREATE TABLE SMALLINT_TYPE_TABLE
(
   SMALLINT_COLUMN smallint
);
CREATE TABLE TIME_TYPE_TABLE
(
   TIME_COLUMN time
);
CREATE TABLE TIMESTAMP_TYPE_TABLE
(
   TIMESTAMP_COLUMN timestamp
);
CREATE TABLE TINYINT_TYPE_TABLE
(
   TINYINT_COLUMN tinyint
);
CREATE TABLE VARBINARY_TYPE_TABLE
(
   VARBINARY_COLUMN varbinary(4194304)
);
CREATE TABLE VARCHAR_TYPE_TABLE
(
   VARCHAR_COLUMN varchar(4194304)
);

