DROP TABLE DBCOPYSRC.BIGINT_TYPE_TABLE;
DROP TABLE DBCOPYSRC.BINARY_TYPE_TABLE;
DROP TABLE DBCOPYSRC.BIT_TYPE_TABLE;
DROP TABLE DBCOPYSRC.BLOB_TYPE_TABLE;
DROP TABLE DBCOPYSRC.BOOLEAN_TYPE_TABLE;
DROP TABLE DBCOPYSRC.CHAR_TYPE_TABLE;
DROP TABLE DBCOPYSRC.CLOB_TYPE_TABLE;
DROP TABLE DBCOPYSRC.DATE_TYPE_TABLE;
DROP TABLE DBCOPYSRC.DECIMAL_TYPE_TABLE;
DROP TABLE DBCOPYSRC.DOUBLE_TYPE_TABLE;
DROP TABLE DBCOPYSRC.FLOAT_TYPE_TABLE;
DROP TABLE DBCOPYSRC.INTEGER_TYPE_TABLE;
DROP TABLE DBCOPYSRC.LONGVARBINARY_TYPE_TABLE;
DROP TABLE DBCOPYSRC.LONGVARCHAR_TYPE_TABLE;
DROP TABLE DBCOPYSRC.NUMERIC_TYPE_TABLE;
DROP TABLE DBCOPYSRC.REAL_TYPE_TABLE;
DROP TABLE DBCOPYSRC.SMALLINT_TYPE_TABLE;
DROP TABLE DBCOPYSRC.TIME_TYPE_TABLE;
DROP TABLE DBCOPYSRC.TIMESTAMP_TYPE_TABLE;
DROP TABLE DBCOPYSRC.TINYINT_TYPE_TABLE;
DROP TABLE DBCOPYSRC.VARBINARY_TYPE_TABLE;
DROP TABLE DBCOPYSRC.VARCHAR_TYPE_TABLE;

CREATE TABLE DBCOPYSRC.BIGINT_TYPE_TABLE
(
   BIGINT_COLUMN BIGINT
);

CREATE TABLE DBCOPYSRC.BINARY_TYPE_TABLE
(
   BINARY_COLUMN BLOB
);

CREATE TABLE DBCOPYSRC.BIT_TYPE_TABLE
(
   BIT_COLUMN SMALLINT
);

CREATE TABLE DBCOPYSRC.BLOB_TYPE_TABLE
(
   BLOB_COLUMN BLOB
);

CREATE TABLE DBCOPYSRC.BOOLEAN_TYPE_TABLE
(
   BOOLEAN_COLUMN SMALLINT
);

CREATE TABLE DBCOPYSRC.CHAR_TYPE_TABLE
(
   CHAR_COLUMN LONG VARCHAR
);

CREATE TABLE DBCOPYSRC.CLOB_TYPE_TABLE
(
   CLOB_COLUMN clob(1073741823)
);

CREATE TABLE DBCOPYSRC.DATE_TYPE_TABLE
(
   DATE_COLUMN DATE
);

CREATE TABLE DBCOPYSRC.DECIMAL_TYPE_TABLE
(
   DECIMAL_COLUMN DECIMAL(31,10)
);

CREATE TABLE DBCOPYSRC.DOUBLE_TYPE_TABLE
(
   DOUBLE_COLUMN FLOAT(53)
);

CREATE TABLE DBCOPYSRC.FLOAT_TYPE_TABLE
(
   FLOAT_COLUMN FLOAT(53)
);

CREATE TABLE DBCOPYSRC.INTEGER_TYPE_TABLE
(
   INTEGER_COLUMN INT
);

CREATE TABLE DBCOPYSRC.LONGVARBINARY_TYPE_TABLE
(
   LONGVARBINARY_COLUMN BLOB(1073741823)
);

CREATE TABLE DBCOPYSRC.LONGVARCHAR_TYPE_TABLE
(
   LONGVARCHAR_COLUMN LONG VARCHAR
);

CREATE TABLE DBCOPYSRC.NUMERIC_TYPE_TABLE
(
   NUMERIC_COLUMN BIGINT
);

CREATE TABLE DBCOPYSRC.REAL_TYPE_TABLE
(
   REAL_COLUMN REAL
);

CREATE TABLE DBCOPYSRC.SMALLINT_TYPE_TABLE
(
   SMALLINT_COLUMN SMALLINT
);

CREATE TABLE DBCOPYSRC.TIME_TYPE_TABLE
(
   TIME_COLUMN TIME
);

CREATE TABLE DBCOPYSRC.TIMESTAMP_TYPE_TABLE
(
   TIMESTAMP_COLUMN TIMESTAMP
);

CREATE TABLE DBCOPYSRC.TINYINT_TYPE_TABLE
(
   TINYINT_COLUMN SMALLINT
);

CREATE TABLE DBCOPYSRC.VARBINARY_TYPE_TABLE
(
   VARBINARY_COLUMN BLOB
);

CREATE TABLE DBCOPYSRC.VARCHAR_TYPE_TABLE
(
   VARCHAR_COLUMN clob(1073741823)
);
