#!/bin/sh
#
# $Id: build,v 1.1.1.1 2001-11-20 01:53:44 placson Exp $
#
# This is the main entry point for the build system.  Users should be sure
# to execute this file rather than 'ant' to ensure the correct version is 
# being used with the correct configuration.
#

# get the name of this program
PROGNAME=`basename $0`

# get the root directory of the project
PROJECT_ROOT=`dirname $0`

#
# Helper to source a file if it exists.
#
maybe_source() {
    file="$1"
    if [ -f "$file" ]; then
	. $file
    fi
}

# if there is a build config file. then source it
maybe_source "$PROJECT_ROOT/build.conf"

##
## Ant Setup
##

# setup the location of ANT_HOME and ANT
if [ "x$ANT_HOME" = "x" ]; then
    ANT_HOME="$PROJECT_ROOT/thirdparty/apache/ant"
fi
export ANT_HOME

if [ "x$ANT" = "x" ]; then
    ANT="$ANT_HOME/bin/ant"
fi
export ANT

# complain if we can't find ant (should not happen if using project-template)
if [ ! -d "$ANT_HOME" ] && [ ! -x "$ANT" ]; then
    echo "${PROGNAME}: Ant was not found in: $ANT_HOME"
    exit 1
fi

# execute
exec $ANT -find "build.xml" "$@"



