package net.sourceforge.squirrel_sql.plugins.i18n;

import net.sourceforge.squirrel_sql.client.IApplication;
import net.sourceforge.squirrel_sql.fw.util.StringManager;
import net.sourceforge.squirrel_sql.fw.util.StringManagerFactory;

import java.io.File;
import java.io.FileOutputStream;
import java.io.PrintWriter;
import java.io.IOException;
import java.util.Properties;
import java.util.Enumeration;

public class I18nBundle implements Comparable
{

   private static final StringManager s_stringMgr =
      StringManagerFactory.getStringManager(I18nProps.class);

   private I18nProps _defaultProps;
   private String _localizedI18nPropsFileName;
   private Integer _missingTranslations;

   /**
    * The localizations that already exist in SQuirreL.
    * When missing props are generated for the first time this
    * Props file will be copied to the work dir.
    */
   private I18nProps _localizedProps;

   public I18nBundle(I18nProps defaultProps, String localizedI18nPropsFileName, File workDir)
   {
      _defaultProps = defaultProps;
      _localizedI18nPropsFileName = localizedI18nPropsFileName;

      Properties buf = _defaultProps.getProperties();
      if(null != _localizedProps)
      {
         _localizedProps.removeProps(buf);
      }

      if(null != workDir)
      {
         File pathInWorkDir = getPathInWorkDir(workDir);
         if(pathInWorkDir.exists())
         {
            new I18nProps(pathInWorkDir).removeProps(buf);
         }
      }

      _missingTranslations = new Integer(buf.size());

   }

   public void setLocalizedProp(I18nProps localizedProps)
   {
      _localizedProps = localizedProps;
   }

   public String toString()
   {
      return _defaultProps.getPath();
   }

   public String getName()
   {
      return _defaultProps.getName();
   }

   public Integer getTranslationState()
   {
      return _missingTranslations;
   }


   public void writeMissingProps(IApplication app, File workDir)
   {
      try
      {
         Properties propsToAppend = _defaultProps.getProperties();

         File toAppendTo = getPathInWorkDir(workDir);
         if(toAppendTo.exists())
         {
            new I18nProps(toAppendTo).removeProps(propsToAppend);
         }
         else
         {
            toAppendTo.getParentFile().mkdirs();
            if(null != _localizedProps)
            {
               _localizedProps.copyTo(toAppendTo);

               Object[] params =
                  new Object[]
                  {
                     _localizedProps.getPath(),
                     toAppendTo.getPath()
                  };

               app.getMessageHandler().showMessage(s_stringMgr.getString("I18n.PropsCopyMsg", params));
               // I18n[I18n.PropsCopyMsg=Copied existing translations from {0} to {1}]

               new I18nProps(toAppendTo).removeProps(propsToAppend);
            }
         }



         FileOutputStream fos = new FileOutputStream(toAppendTo, true);
         PrintWriter pw = new PrintWriter(fos);

         pw.println(s_stringMgr.getString("I18n.PropsGenerationMessage", new java.util.Date()));
         // I18n[I18n.PropsGenerationMessage=\n#\n#Missing translation generated by I18n Plugin on {0}\n#]

         for(Enumeration e=propsToAppend.keys(); e.hasMoreElements();)
         {
            String key = (String) e.nextElement();
            String val = propsToAppend.getProperty(key);

            pw.println("#" + key + "=" + normalizePropVal(val));
            pw.println("#" + key + "=");
         }

         pw.flush();
         fos.flush();

         pw.close();
         fos.close();

         Object[] params =
            new Object[]
            {
               new Integer(propsToAppend.size()),
               toAppendTo.getPath()
            };

         app.getMessageHandler().showMessage(s_stringMgr.getString("I18n.PropsGenerationCount", params));
         // I18n[I18n.PropsGenerationCount=Generated {0} templates to {1}]
      }
      catch (IOException e)
      {
         throw new RuntimeException(e);
      }

   }

   File getPathInWorkDir(File workDir)
   {
      File toAppendTo = new File(workDir.getPath() + File.separator + getName());
      toAppendTo = new File(toAppendTo.getParent() + File.separator + _localizedI18nPropsFileName);
      return toAppendTo;
   }

   private String normalizePropVal(String val)
   {
      return val.replaceAll("\\n", "\\\\n");
   }


   public int compareTo(Object other)
   {
      return getName().compareTo(((I18nBundle)other).getName());


   }
}
