CREATE TABLE A_LG_CLOB_TEST
(
   MYCLOB clob
)
;
CREATE TABLE ADDRESS
(
   LASTNAME varchar2(25),
   FIRSTNAME varchar2(25),
   STREET varchar2(50),
   CITY varchar2(25),
   STATE varchar2(2),
   ZIP decimal(19),
   PHONE varchar2(12),
   EXT varchar2(5)
)
;
CREATE TABLE AREAS
(
   RADIUS decimal(19),
   AREA decimal(14)
)
;
CREATE TABLE AUTHOR
(
   AUTHORNAME varchar2(50) PRIMARY KEY NOT NULL,
   COMMENTS varchar2(100)
)
;
CREATE TABLE BIGINT_TYPE_TABLE
(
   BIGINT_COLUMN decimal(19),
   PKCOL decimal(19) PRIMARY KEY NOT NULL,
   NEWCOLUMN varchar2(10)
)
;
CREATE TABLE BIGINT_VIEW
(
   BIGINT_COLUMN decimal(19)
)
;
CREATE TABLE BIGINT_VIEW2
(
   BIGINT_COLUMN decimal(19),
   INTEGER_COLUMN decimal(19)
)
;
CREATE TABLE BINARY_TYPE_TABLE
(
   BINARY_COLUMN blob
)
;
CREATE TABLE BIRTHDAY
(
   FIRSTNAME varchar2(15) NOT NULL,
   LASTNAME varchar2(15) NOT NULL,
   BIRTHDATE timestamp,
   AGE decimal(19),
   CONSTRAINT SYS_C0031035 PRIMARY KEY (FIRSTNAME,LASTNAME)
)
;
CREATE TABLE BIT_TYPE_TABLE
(
   BIT_COLUMN decimal(19)
)
;
CREATE TABLE BLOB_TYPE_TABLE
(
   BLOB_COLUMN blob
)
;
CREATE TABLE BOOK_ORDER
(
   TITLE varchar2(100) PRIMARY KEY NOT NULL,
   PUBLISHER varchar2(20),
   CATEGORYNAME varchar2(20)
)
;
CREATE TABLE BOOK_REVIEW_CONTEXT
(
   TITLE varchar2(100) PRIMARY KEY NOT NULL,
   REVIEWER varchar2(25),
   REVIEW_DATE timestamp,
   REVIEW_TEXT varchar2(4000)
)
;
CREATE TABLE BOOK_REVIEW_CTXCAT
(
   TITLE varchar2(100) PRIMARY KEY NOT NULL,
   REVIEWER varchar2(25),
   REVIEW_DATE timestamp,
   REVIEW_TEXT varchar2(4000)
)
;
CREATE TABLE BOOKSHELF
(
   TITLE varchar2(100) PRIMARY KEY NOT NULL,
   PUBLISHER varchar2(20),
   CATEGORYNAME varchar2(20),
   RATING varchar2(2)
)
;
CREATE TABLE BOOKSHELF_AUDIT
(
   TITLE varchar2(100),
   PUBLISHER varchar2(20),
   CATEGORYNAME varchar2(20),
   OLD_RATING varchar2(2),
   NEW_RATING varchar2(2),
   AUDIT_DATE timestamp
)
;
CREATE TABLE BOOKSHELF_AUTHOR
(
   TITLE varchar2(100),
   AUTHORNAME varchar2(50)
)
;
CREATE TABLE BOOKSHELF_CHECKOUT
(
   NAME varchar2(25),
   TITLE varchar2(100),
   CHECKOUTDATE timestamp,
   RETURNEDDATE timestamp
)
;
CREATE TABLE BOOLEAN_TYPE_TABLE
(
   BOOLEAN_COLUMN decimal(19)
)
;
CREATE TABLE CHAR_TYPE_TABLE
(
   CHAR_COLUMN clob
)
;
CREATE TABLE CLOB_TYPE_TABLE
(
   CLOB_COLUMN clob
)
;
CREATE TABLE DATE_TYPE_TABLE
(
   DATE_COLUMN timestamp
)
;
CREATE TABLE DATE_TYPE_TABLE2
(
   DATE_COLUMN timestamp
)
;
CREATE TABLE DECIMAL_TYPE_TABLE
(
   DECIMAL_COLUMN decimal(19)
)
;
CREATE TABLE DOUBLE_TYPE_TABLE
(
   DOUBLE_COLUMN float(17)
)
;
CREATE TABLE EDIT_TEST
(
   ID decimal(19) PRIMARY KEY NOT NULL,
   TEXT varchar2(32) NOT NULL,
   NUM decimal(19),
   DESCRIPTION varchar2(255),
   INSERT_DT timestamp NOT NULL
)
;
CREATE TABLE FLOAT_TYPE_TABLE
(
   FLOAT_COLUMN float(17)
)
;
CREATE TABLE INTEGER_TYPE_TABLE
(
   INTEGER_COLUMN decimal(19)
)
;
CREATE TABLE LOCATION
(
   CITY varchar2(25),
   COUNTRY varchar2(25),
   CONTINENT varchar2(25),
   LATITUDE decimal(19),
   NORTHSOUTH varchar2(1),
   LONGITUDE decimal(19),
   EASTWEST varchar2(1)
)
;
CREATE TABLE LONGVARBINARY_TYPE_TABLE
(
   LONGVARBINARY_COLUMN blob
)
;
CREATE TABLE LONGVARCHAR_TYPE_TABLE
(
   LONGVARCHAR_COLUMN clob
)
;
CREATE TABLE MAGAZINE
(
   NAME varchar2(16),
   TITLE varchar2(37),
   AUTHOR varchar2(25),
   ISSUEDATE timestamp,
   PAGE decimal(19)
)
;
CREATE TABLE MATH
(
   NAME varchar2(12),
   ABOVE decimal(19),
   BELOW decimal(19),
   EMPTY decimal(19)
)
;
CREATE TABLE MESSAGES
(
   MESSAGE_ID decimal(19) PRIMARY KEY NOT NULL,
   MESSAGE_TEXT varchar2(255),
   NEXT_MESSAGE_ID decimal(19)
)
;
CREATE TABLE NUMERIC_TYPE_TABLE
(
   NUMERIC_COLUMN decimal(19)
)
;
CREATE TABLE REAL_TYPE_TABLE
(
   REAL_COLUMN float(17)
)
;
CREATE TABLE SMALLINT_TYPE_TABLE
(
   SMALLINT_COLUMN decimal(19)
)
;
CREATE TABLE TEST1
(
   MYCHAR varchar2(10),
   NULLINT decimal(19)
)
;
CREATE TABLE TEST2
(
   MYCHAR varchar2(10),
   NOTNULLINT decimal(19)
)
;
CREATE TABLE TIME_TYPE_TABLE
(
   TIME_COLUMN timestamp,
   NEWCOLUMN clob,
   NEWCOLUMN2 clob
)
;
CREATE TABLE TIMESTAMP_TYPE_TABLE
(
   TIMESTAMP_COLUMN timestamp
)
;
CREATE TABLE TINYINT_TYPE_TABLE
(
   TINYINT_COLUMN decimal(19)
)
;
CREATE TABLE VARBINARY_TYPE_TABLE
(
   VARBINARY_COLUMN blob
)
;
CREATE TABLE VARCHAR_TYPE_TABLE
(
   VARCHAR_COLUMN clob
)
;

